[package]
name = "trust-list"
version = "0.1.5"
edition = "2021"
license = "MIT"
keywords = ["trust", "dependencies", "cargo-subcommand", "tool"]
readme = "README.md"
description = "Command line tool for automatically generating dependency information tables in markdown"
homepage = "https://github.com/lhalf/trust-list-rs"
repository = "https://github.com/lhalf/trust-list-rs"

[dependencies]
clap = { version = "*", features = ["derive"] }
anyhow = "*"
itertools = "*"
reqwest = { version = "*", features = ["blocking"] }
serde_json = "*"
serde = { version = "*", features = ["derive"] }
chrono = { version = "*", features = ["serde"] }
pbr = "*"